name: goreleaser

on:
  push:
    branches:
      - "release/*"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest    
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      - uses: actions/checkout@v2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
